FROM otel/opentelemetry-collector-contrib:0.143.0

COPY observability/otel-collector.yaml /etc/otel-collector-config.yaml

ENTRYPOINT ["/otelcol-contrib"]
CMD ["--config=/etc/otel-collector-config.yaml"]
